"""empty message

Revision ID: 745d708bc5fa
Revises: 9e235a4a8c63
Create Date: 2023-06-20 21:37:05.741318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745d708bc5fa'
down_revision = '9e235a4a8c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcode', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
